language: node_js
env:
  - NODE_VERSION="0.10.29"
  - NODE_VERSION="0.11.13"
node_js:
  - "0.10"
  - "0.11"
notifications:
  email:
    - rick68@gmail.com
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4
  - export CXXFLAGS="-stdlib=libc++"
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - cd libcxx/lib && bash buildit
  - sudo cp ./libc++.so.1.0 /usr/lib/
  - sudo mkdir /usr/include/c++/v1
  - cd .. && sudo cp -r include/* /usr/include/c++/v1/
  - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
  - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
  - export CXX="clang++"
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  # at this point Travis-CI will implicitly run `npm install` for us
